### ISSUE TITLE
Use Intergen PnP

### ISSUE THREAD

**Issue by sethreidnz** [Intergen-NZ/modern-apps-grad-handbook#6]
Why are we still maintaining a separate piece of documentation? Not trying to be disparaging but we have a specific project for this now and working on this on the side is counterproductive.

I've created a card in the Planning area of VSTS so we can track and manage moving anything you think is not already covered in out intro docs (we went for generic intro docs not grad docs, if you think there is a reason to have separate docs for grads then feel free to chime in on the card). Open to discussion but we are trying to standardize so having everything in one place is step 1.

**Comment by sethreidnz** [comment]
I can see the value from a marketing point of view though. I'd like to see more of this. I just don't want to see the same documentation in two places and people working on this when there are 1000s of things to do in PnP

**Comment by aquibm** [comment]
> we have a specific project for this now and working on this on the side is counterproductive.

It's not accessible by future grads and is therefore not in line with why this list was created.

What we're trying to do here is outline the tech we're passionate about rather than documenting recipes specific to Intergen.

**Comment by sethreidnz** [comment]
Fair enough makes sense! I only raised issue cuz I've emailed a few times
and got no reply. IF this is sanctioned by Toby I don't care then. But I
think this info ALSO should be in the handbook. :-)


Seth Reid | Web Consultant/Developer

0221705966 | contact@sethreid.co.nz
